spring:
  datasource:
    url: jdbc:mysql://${DB_ADDRESS:localhost}:${DB_PORT:3306}/${DB_DATABASE:smarter}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
server:
  error:
    include-message: always
  servlet:
    context-path: /smarter/api/v1
  port: ${BASE_PORT:8080}
springdoc:
  swagger-ui:
    path: /smarter/api/v1/swagger-ui.html
  api-docs:
    path: /smarter/api/v1/docs