spring:
  datasource:
    url: jdbc:mysql://${smarter.DB_ADDRESS:localhost}:${smarter.DB_PORT:3306}/${smarter.DB_DATABASE:smarter_backend}?createDatabaseIfNotExist=true
    username: ${smarter.DB_USERNAME}
    password: ${smarter.DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: ${smarter.EMAIL_USERNAME}
    password: ${smarter.EMAIL_PASSWORD}
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
  config:
    import: optional:secrets.yaml
server:
  error:
    include-message: always
  servlet:
    context-path: /smarter/api/v1
  port: ${smarter.BASE_PORT:8080}
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs